"""Working Memory Store (component 09): task-scoped key-value store with
provenance.

Responsibility: hold extracted values with provenance for the duration of
a task, keyed by step ID, so later steps reference data rather than having
it re-generated by the LLM. Contract: docs/Component_IO_Spec.md, section 9.

Ported from the working prototype in part4/memory.py (a `WorkingMemory`
class keyed by task_id), reshaped into this component's documented
single-dict-in/single-dict-out `set_or_get` entry point plus a couple of
extra module-level helpers (`resolve_ref`, `get_provenance`) that the
execution node needs and that the IO spec's standalone-test note calls
out explicitly ("test set/get/clear operations and TTL/scope-per-task
cleanup").
"""
import time
from threading import Lock
from typing import Any

# task_id -> {key: {"value": ..., "provenance": ..., "set_at": float}}
_store: dict[str, dict[str, dict[str, Any]]] = {}
_lock = Lock()

_DEFAULT_TASK_ID = "default"


def set_or_get(request: dict[str, Any]) -> dict[str, Any]:
    """Apply one working-memory operation.

    request: {"operation": "set"|"get"|"clear", "task_id"?, "key"?, "value"?, "provenance"?}
    "task_id" defaults to a single shared scope when omitted, but callers
    driving multiple concurrent tasks (e.g. one per voice session) should
    always pass it explicitly to keep tasks isolated.
    """
    operation = request.get("operation")
    task_id = request.get("task_id") or _DEFAULT_TASK_ID

    if operation == "set":
        key = request["key"]
        with _lock:
            _store.setdefault(task_id, {})[key] = {
                "value": request.get("value"),
                "provenance": request.get("provenance") or {},
                "set_at": time.time(),
            }
        return {"key": key, "value": request.get("value"), "provenance": request.get("provenance") or {}}

    if operation == "get":
        key = request["key"]
        with _lock:
            record = _store.get(task_id, {}).get(key)
        if record is None:
            return {"key": key, "value": None, "provenance": {}}
        return {"key": key, "value": record["value"], "provenance": record["provenance"]}

    if operation == "clear":
        with _lock:
            _store.pop(task_id, None)
        return {"task_id": task_id, "cleared": True}

    raise ValueError(f"Unknown operation '{operation}'")


def resolve_ref(task_id: str, value_or_ref: Any) -> Any:
    """Resolve a `step_N.value`-style reference to its stored value.

    Falls through unchanged if `value_or_ref` isn't a key currently held
    for this task — i.e. it was already a literal value, not a reference.
    """
    with _lock:
        record = _store.get(task_id, {}).get(value_or_ref) if isinstance(value_or_ref, str) else None
    return record["value"] if record is not None else value_or_ref


def get_provenance(task_id: str, key: str) -> dict[str, Any] | None:
    with _lock:
        record = _store.get(task_id, {}).get(key)
    return record["provenance"] if record is not None else None
